crd:
  kind: NetworkTestSuite
  plural: networktestsuites
  singular: networktestsuite
  group: kubekarma.io
  scope: Namespaced
  shortNames:
    - npts
image:
  repository: localhost:5000/network-policy-test-operator
  pullPolicy: IfNotPresent
  tag: "latest"
workerImage:
  repository: localhost:5000/network-policy-test-worker
  pullPolicy: IfNotPresent
  tag: "latest"
