apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networktestsuites.kubekarma.io
spec:
  scope: Namespaced
  preserveUnknownFields: false
  group: kubekarma.io
  names:
    kind: NetworkTestSuite
    plural: networktestsuites
    singular: networktestsuite
    shortNames:
      - nptest
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the test suite
                schedule:
                  type: string
                  description: The frequency at which the test suite should be run
                  default: "* * * * *"
                  pattern: "^[*] ([*]|[0-5]?[0-9]) ([*]|[0-5]?[0-9]) ([*]|[0-9]|[0-2]?[0-9]) ([*]|[0-9]|[0-6]?[0-9])$"
                networkValidations:
                  type: array
                  items:
                    type: object
                    properties:
                      allowedToFail:
                        type: boolean
                        description: If true, the test case will not cause the test suite to fail
                        default: false
                      name:
                        type: string
                        description: The name of the test case
                      testExactDestination:
                        type: object
                        properties:
                          destinationIP:
                            type: string
                          port:
                            type: integer
                          expectSuccess:
                            type: boolean
                          protocol:
                            type: string
                            enum:
                              - TCP
                              - UDP
                            default: TCP
                        required:
                          - destinationIP
                          - port
                          - expectSuccess
                      testIpBlock:
                        type: object
                        properties:
                          ipBlock:
                            type: string
                          destinationPort:
                            type: integer
                          expectSuccess:
                            type: boolean
                        required:
                          - ipBlock
                          - destinationPort
                          - expectSuccess
                      destinationHost:
                          type: object
                          properties:
                            host:
                              type: string
                            port:
                              type: integer
                            expectSuccess:
                              type: boolean
                          required:
                              - host
                              - port
                              - expectSuccess
                      testDNSResolution:
                        type: object
                        properties:
                          nameservers:
                            type: array
                            items:
                              type: string
                          host:
                            type: string
                          expectSuccess:
                            type: boolean
                        required:
                          - host
                          - expectSuccess
                    oneOf:
                      - properties:
                        required:
                          - testDNSResolution
                      - properties:
                        required:
                          - testExactDestination
                      - properties:
                        required:
                          - testIpBlock
                      - properties:
                        required:
                          - destinationHost
                    required:
                      - name
                suspend:
                  type: boolean
                  description: If true, the test suite will not be executed
                  default: false
              required:
                - name
                - networkValidations
            status:
              type: object
              # Required to allow patch status with KOPF :/
              x-kubernetes-preserve-unknown-fields: true
              properties:
                phase:
                  type: string
                  description: The current status of the test suite
                  default: Pending
                  enum:
                    - Pending # The test suite has not started yet
                    - Active
                    - Failed
                    - Suspended
                testExecutionStatus:
                  description: The status of the whole test suite
                  type: string
                  enum:
                      - Pending # The test suite has not started yet
                      - Succeeding # The test suite is running and all the test cases are passing
                      - Failing # The test suite is running and at least one test case is failing

                # @status.networkValidations is an array with information about each test case
                networkValidations:
                  type: array
                  default: []
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: The name of the test case (As unique identifier)
                      status:
                        type: string
                        description: The current status of the test case
                        enum:
                          - Failed
                          - Succeeded
                          - NotImplemented
                          - Error
                      error:
                        type: string
                        description: If for any reason the test fails with an unexpected error, this field will contain the error message
                      executionTime:
                        type: string
                        description: The time it took to execute the test case
                    required:
                      - name # name is required because is like an UID
                      - status
                lastExecutionTime:
                  type: string
                  description: The last time the test case was executed
                lastExecutionErrorTime:
                  type: string
                  description: The last error that occurred when executing the test case
                lastSucceededTime:
                  type: string
                  description: The last time the test case was executed successfully
                passingCount:
                  type: string
                  description: The number of test cases that passed (Succeeded/Total)
              required:
                - phase
                - networkValidations
      additionalPrinterColumns:
      - name: Phase
        type: string
        description: The phase of the CRD
        jsonPath: .status.phase
      - name: Passing
        type: string
        description: The number of test cases passed/total
        jsonPath: .status.passingCount
      - name: Status
        type: string
        description: The status of the whole test suite
        jsonPath: .status.testExecutionStatus
      - name: Last Execution
        type: date
        format: date-time
        description: The last time the test suite was executed
        jsonPath: .status.lastExecutionTime
      - name: Last failure
        type: date
        description: The last time error that occurred when executing the test suite
        jsonPath: .status.lastExecutionErrorTime
      # https://github.com/kubernetes-sigs/controller-tools/issues/447
      - name: Age
        type: date
        description: The age of the suite
        jsonPath: .metadata.creationTimestamp