---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-operator
spec:
  # To allow more replicas, first we need to implement in the controller the
  # logic to avoid controller receiving reports when it is not the leader.
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-operator
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-operator
    spec:
      serviceAccountName: {{ .Release.Name }}-account
      containers:
      - name: {{ include "chart.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 8000
          - containerPort: {{ .Values.controller.grpc.port }}
            name: grpcsrv
        env:
        - name: EXPOSED_CONTROLLER_GRPC_ADDRESS # The absolute url of the controller grpc server
          value: '{{ include "svc.headless-grpc-service-name" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.controller.grpc.port }}'
        - name: WORKER_DOCKER_IMAGE
          value: {{ .Values.workerImage.repository }}:{{ .Values.workerImage.tag }}
        - name: LOG_LEVEL
          value: {{ required ".controller.logLevel is required" .Values.controller.logLevel }}
        livenessProbe:
          grpc:
            port: {{ .Values.controller.grpc.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 10
          initialDelaySeconds: 5

{{/*        readinessProbe:*/}}
{{/*          grpc:*/}}
{{/*            port: {{ .Values.controller.grpc.port }}*/}}
