---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-operator
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-operator
    spec:
      serviceAccountName: {{ .Release.Name }}-account
      containers:
      - name: {{ include "chart.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8000
        env:
        - name: OPERATOR_SVC_HOST
          value: {{ include "svc.headless-service-url" . | quote }}
        livenessProbe:
          httpGet:
            port: 8000
            path: /healthz

          initialDelaySeconds: 30
          periodSeconds: 10
