---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-operator
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-operator
    spec:
      serviceAccountName: {{ .Release.Name }}-account
      containers:
      - name: {{ include "chart.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 8000
          - containerPort: {{ .Values.controller.grpc.port }}
            name: grpcsrv
        env:
        - name: EXPOSED_CONTROLLER_GRPC_ADDRESS # The absolute url of the controller grpc server
          value: '{{ include "svc.headless-grpc-service-name" . }}{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.controller.grpc.port }}'
        - name: WORKER_DOCKER_IMAGE
          value: {{ .Values.workerImage.repository }}:{{ .Values.workerImage.tag }}
        livenessProbe:
          grpc:
            port: {{ .Values.controller.grpc.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          grpc:
            port: {{ .Values.controller.grpc.port }}
          initialDelaySeconds: 5