---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "svc.headless-service-name" . }}
  labels:
    app: {{ include "svc.headless-service-name" . }}
spec:
  clusterIP: None
  ports:
  - port: 8000
    name: http
  selector:
      app: {{ .Release.Name }}-operator