---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "svc.headless-grpc-service-name" . }}
  labels:
    app: {{ include "svc.headless-grpc-service-name" . }}
spec:
  clusterIP: None
  selector:
      app: {{ .Release.Name }}-operator
  ports:
      - protocol: TCP
        port: {{ .Values.controller.grpc.service.port }}
        targetPort: grpcsrv
        name: grpcsrv