"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class TestCaseResult(google.protobuf.message.Message):
    """*
    TestCaseResult represents and individual test case result
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _TestStatus:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TestStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TestCaseResult._TestStatus.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        ERROR: TestCaseResult._TestStatus.ValueType  # 0
        """ERROR: when some exception was raised during the execution of the test case"""
        SUCCEEDED: TestCaseResult._TestStatus.ValueType  # 1
        """SUCCEEDED: when the test case was executed successfully"""
        FAILED: TestCaseResult._TestStatus.ValueType  # 2
        """FAILED: when the test case was executed but the assertion failed"""
        NOT_IMPLEMENTED: TestCaseResult._TestStatus.ValueType  # 3
        """NOTIMPLEMENTED: when the test case code is not implemented yet"""

    class TestStatus(_TestStatus, metaclass=_TestStatusEnumTypeWrapper): ...
    ERROR: TestCaseResult.TestStatus.ValueType  # 0
    """ERROR: when some exception was raised during the execution of the test case"""
    SUCCEEDED: TestCaseResult.TestStatus.ValueType  # 1
    """SUCCEEDED: when the test case was executed successfully"""
    FAILED: TestCaseResult.TestStatus.ValueType  # 2
    """FAILED: when the test case was executed but the assertion failed"""
    NOT_IMPLEMENTED: TestCaseResult.TestStatus.ValueType  # 3
    """NOTIMPLEMENTED: when the test case code is not implemented yet"""

    NAME_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    EXECUTION_DURATION_FIELD_NUMBER: builtins.int
    EXECUTION_START_TIME_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The specific name of the test case"""
    status: global___TestCaseResult.TestStatus.ValueType
    execution_duration: builtins.str
    """How long it took to execute the test case"""
    execution_start_time: builtins.str
    """When the test case started executing"""
    error_message: builtins.str
    """errorMessage is only set when the status is ERROR and it contains the
    exception message and stack trace
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        status: global___TestCaseResult.TestStatus.ValueType = ...,
        execution_duration: builtins.str = ...,
        execution_start_time: builtins.str = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["error_message", b"error_message", "execution_duration", b"execution_duration", "execution_start_time", b"execution_start_time", "name", b"name", "status", b"status"]) -> None: ...

global___TestCaseResult = TestCaseResult

@typing_extensions.final
class ProcessTestSuiteResultsRequest(google.protobuf.message.Message):
    """*
    TestSuiteResult represents the result of a whole test suite execution
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    STARTED_AT_TIME_FIELD_NUMBER: builtins.int
    TEST_CASE_RESULTS_FIELD_NUMBER: builtins.int
    TOKEN_FIELD_NUMBER: builtins.int
    name: builtins.str
    """name: is the name of the test suite"""
    started_at_time: builtins.str
    """the time when the test suite started executing
    it should be in ISO 8601 format
    """
    @property
    def test_case_results(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TestCaseResult]: ...
    token: builtins.str
    """token: is used to identify the test suite execution"""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        started_at_time: builtins.str = ...,
        test_case_results: collections.abc.Iterable[global___TestCaseResult] | None = ...,
        token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name", "started_at_time", b"started_at_time", "test_case_results", b"test_case_results", "token", b"token"]) -> None: ...

global___ProcessTestSuiteResultsRequest = ProcessTestSuiteResultsRequest

@typing_extensions.final
class ProcessTestSuiteResultsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    message: builtins.str
    def __init__(
        self,
        *,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message"]) -> None: ...

global___ProcessTestSuiteResultsResponse = ProcessTestSuiteResultsResponse
