#!/bin/bash -exworkerImage:
  repository: localhost:5000/network-policy-test-worker
  pullPolicy: IfNotPresent
  tag: "ff4997e-dirty"

SKAFFOLD_IMAGE="${SKAFFOLD_IMAGE:?SKAFFOLD_IMAGE is not set}"


yq -e -i '.workerImage.tag = strenv(SKAFFOLD_IMAGE_TAG)' dev/values.yaml
