"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import collections.abc
import grpc
import grpc.aio
import kubekarma.grpcgen.collectors.v1alpha.controller_pb2
import typing

_T = typing.TypeVar('_T')

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta):
    ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore
    ...

class TestSuiteExecutionResultServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    ReportResults: grpc.UnaryUnaryMultiCallable[
        kubekarma.grpcgen.collectors.v1alpha.controller_pb2.ExecutionResultRequest,
        kubekarma.grpcgen.collectors.v1alpha.controller_pb2.ExecutionResultResponse,
    ]
    """ProcessTestSuiteResults is called by the test runner to report the results of the execution"""

class TestSuiteExecutionResultServiceAsyncStub:
    ReportResults: grpc.aio.UnaryUnaryMultiCallable[
        kubekarma.grpcgen.collectors.v1alpha.controller_pb2.ExecutionResultRequest,
        kubekarma.grpcgen.collectors.v1alpha.controller_pb2.ExecutionResultResponse,
    ]
    """ProcessTestSuiteResults is called by the test runner to report the results of the execution"""

class TestSuiteExecutionResultServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def ReportResults(
        self,
        request: kubekarma.grpcgen.collectors.v1alpha.controller_pb2.ExecutionResultRequest,
        context: _ServicerContext,
    ) -> typing.Union[kubekarma.grpcgen.collectors.v1alpha.controller_pb2.ExecutionResultResponse, collections.abc.Awaitable[kubekarma.grpcgen.collectors.v1alpha.controller_pb2.ExecutionResultResponse]]:
        """ProcessTestSuiteResults is called by the test runner to report the results of the execution"""

def add_TestSuiteExecutionResultServiceServicer_to_server(servicer: TestSuiteExecutionResultServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
