# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kubekarma.grpcgen.collectors.v1alpha import controller_pb2 as kubekarma_dot_grpcgen_dot_collectors_dot_v1alpha_dot_controller__pb2


class TestSuiteExecutionResultServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportResults = channel.unary_unary(
                '/kubekarma.collectors.v1alpha.TestSuiteExecutionResultService/ReportResults',
                request_serializer=kubekarma_dot_grpcgen_dot_collectors_dot_v1alpha_dot_controller__pb2.ExecutionResultRequest.SerializeToString,
                response_deserializer=kubekarma_dot_grpcgen_dot_collectors_dot_v1alpha_dot_controller__pb2.ExecutionResultResponse.FromString,
                )


class TestSuiteExecutionResultServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReportResults(self, request, context):
        """ProcessTestSuiteResults is called by the test runner to report the results of the execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestSuiteExecutionResultServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportResults': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportResults,
                    request_deserializer=kubekarma_dot_grpcgen_dot_collectors_dot_v1alpha_dot_controller__pb2.ExecutionResultRequest.FromString,
                    response_serializer=kubekarma_dot_grpcgen_dot_collectors_dot_v1alpha_dot_controller__pb2.ExecutionResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kubekarma.collectors.v1alpha.TestSuiteExecutionResultService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestSuiteExecutionResultService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kubekarma.collectors.v1alpha.TestSuiteExecutionResultService/ReportResults',
            kubekarma_dot_grpcgen_dot_collectors_dot_v1alpha_dot_controller__pb2.ExecutionResultRequest.SerializeToString,
            kubekarma_dot_grpcgen_dot_collectors_dot_v1alpha_dot_controller__pb2.ExecutionResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
