crd:
  kind: NetworkTestSuite
  plural: networktestsuites
  singular: networktestsuite
  group: kubekarma.io
  scope: Namespaced
  shortNames:
    - npts
image:
  repository: steib/kubekarma-operator:latest
  pullPolicy: IfNotPresent
  tag: "latest"
workerImage:
  repository: steib/kubekarma:latest
  pullPolicy: IfNotPresent
  tag: "latest"


controller:
  grpc:
    address: "[::]"
    port: 8080
    service:
      # @controller.grpcsrv.service.port the exposed port by the service
      port: 8080
