crd:
  kind: NetworkTestSuite
  plural: networktestsuites
  singular: networktestsuite
  group: kubekarma.io
  scope: Namespaced
  shortNames:
    - npts
image:
  repository: steib/kubekarma-operator
  pullPolicy: IfNotPresent
  tag: "latest"
workerImage:
  repository: steib/kubekarma
  pullPolicy: IfNotPresent
  tag: "latest"


controller:
  grpc:
    address: "[::]"
    port: 8080
    service:
      # @controller.grpcsrv.service.port the exposed port by the service
      port: 8080
  # @controller.logLevel defines the default log level for the controller logs
  logLevel: "info"