# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kubekarma.shared.pb2 import controller_pb2 as kubekarma_dot_shared_dot_pb2_dot_controller__pb2


class ControllerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessTestSuiteResults = channel.unary_unary(
                '/ControllerService/ProcessTestSuiteResults',
                request_serializer=kubekarma_dot_shared_dot_pb2_dot_controller__pb2.ProcessTestSuiteResultsRequest.SerializeToString,
                response_deserializer=kubekarma_dot_shared_dot_pb2_dot_controller__pb2.ProcessTestSuiteResultsResponse.FromString,
                )


class ControllerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessTestSuiteResults(self, request, context):
        """ProcessTestSuiteResults is called by the test runner to report the results of the execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessTestSuiteResults': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessTestSuiteResults,
                    request_deserializer=kubekarma_dot_shared_dot_pb2_dot_controller__pb2.ProcessTestSuiteResultsRequest.FromString,
                    response_serializer=kubekarma_dot_shared_dot_pb2_dot_controller__pb2.ProcessTestSuiteResultsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ControllerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ControllerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessTestSuiteResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ControllerService/ProcessTestSuiteResults',
            kubekarma_dot_shared_dot_pb2_dot_controller__pb2.ProcessTestSuiteResultsRequest.SerializeToString,
            kubekarma_dot_shared_dot_pb2_dot_controller__pb2.ProcessTestSuiteResultsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
