# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kubekarma/shared/pb2/controller.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%kubekarma/shared/pb2/controller.proto\"\x8c\x01\n\x0eTestCaseResult\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1b\n\x06status\x18\x02 \x01(\x0e\x32\x0b.TestStatus\x12\x1a\n\x12\x65xecution_duration\x18\x03 \x01(\t\x12\x1c\n\x14\x65xecution_start_time\x18\x04 \x01(\t\x12\x15\n\rerror_message\x18\x05 \x01(\t\"i\n\x1eProcessTestSuiteResultsRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12*\n\x11test_case_results\x18\x02 \x03(\x0b\x32\x0f.TestCaseResult\x12\r\n\x05token\x18\x03 \x01(\t\"2\n\x1fProcessTestSuiteResultsResponse\x12\x0f\n\x07message\x18\x01 \x01(\t*F\n\nTestStatus\x12\t\n\x05\x45RROR\x10\x00\x12\r\n\tSUCCEEDED\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x12\x12\n\x0eNOTIMPLEMENTED\x10\x03\x32s\n\x11\x43ontrollerService\x12^\n\x17ProcessTestSuiteResults\x12\x1f.ProcessTestSuiteResultsRequest\x1a .ProcessTestSuiteResultsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kubekarma.shared.pb2.controller_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TESTSTATUS']._serialized_start=343
  _globals['_TESTSTATUS']._serialized_end=413
  _globals['_TESTCASERESULT']._serialized_start=42
  _globals['_TESTCASERESULT']._serialized_end=182
  _globals['_PROCESSTESTSUITERESULTSREQUEST']._serialized_start=184
  _globals['_PROCESSTESTSUITERESULTSREQUEST']._serialized_end=289
  _globals['_PROCESSTESTSUITERESULTSRESPONSE']._serialized_start=291
  _globals['_PROCESSTESTSUITERESULTSRESPONSE']._serialized_end=341
  _globals['_CONTROLLERSERVICE']._serialized_start=415
  _globals['_CONTROLLERSERVICE']._serialized_end=530
# @@protoc_insertion_point(module_scope)
