name: ci

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

env:
  OPERATOR_REPOSITORY: ${{ vars.DOCKER_OPERATOR_REPOSITORY }}
  WORKER_REPOSITORY: ${{ vars.DOCKER_WORKER_REPOSITORY }}

jobs:
  run-tests:
    name: Run python validations
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install tox and any other packages
      run: pip install tox
    - name: Run import linter
      run: tox -e lint-imports
    - name: Run test worker
      run: tox -e test-worker
  docker-images:
    uses: ./.github/workflows/workflow-docker-images.yaml
    name: Docker images
    with:
      username: ${{ vars.DOCKERHUB_USERNAME }}
      operator_repository: ${{ vars.DOCKER_OPERATOR_REPOSITORY }}
      worker_repository: ${{ vars.DOCKER_WORKER_REPOSITORY }}
      push: false
    secrets:
      token: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: "Docker: publish worker image"
#        uses: docker/build-push-action@v5
#        with:
#          push: ${{ github.event_name != 'pull_request' }}
#          load: true
#          tags: ${{ steps.meta-worker.outputs.tags }}
#          labels: ${{ steps.meta-worker.outputs.labels }}
#          file: ./worker.Dockerfile
#      - name: "Docker: publish operator image"
#        uses: docker/build-push-action@v5
#        with:
#          push: ${{ github.event_name != 'pull_request' }}
#          load: true
#          tags: ${{ steps.meta-operator.outputs.tags }}
#          labels: ${{ steps.meta-operator.outputs.labels }}
#          file: ./operator.Dockerfile