name: ci

on: [push]

jobs:
  run-tests:
    name: Run python validations
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install tox and any other packages
      run: pip install tox
    - name: Run import linter
      run: tox -e lint-imports
    - name: Run test worker
      run: tox -e test-worker
  Build-Docker:
    runs-on: ubuntu-latest
    name: Build docker images
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build operator image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ${{ vars.DOCKER_REPOSITORY }}:operator-latest
          file: ./operator.Dockerfile
      - name: Build worker image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ${{ vars.DOCKER_REPOSITORY }}:worker-latest
          file: ./worker.Dockerfile
