name: Docker images

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
        description: 'Docker Hub username'
    secrets:
      token:
        required: true
        description: 'Docker Hub token'

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ secrets.token }}
