name: Docker images

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean
        description: 'Push images to Docker Hub'
      username:
        required: true
        type: string
        description: 'Docker Hub username'
      operator_repository:
        required: true
        type: string
        description: 'Docker Hub repository for operator image'
      worker_repository:
        required: true
        type: string
        description: 'Docker Hub repository for worker image'
    secrets:
      token:
        required: true
        description: 'Docker Hub token'

jobs:
  triage:
    name: "Build & Test and maybe Push"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ secrets.token }}
    - name: "Docker: metadata-action for operator"
      id: meta-operator
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.operator_repository }}
        labels: |
          org.opencontainers.image.title=KubeKarma Operator
          org.opencontainers.image.url=https://github.com/cristiansteib/kubekarma/blob/${{ github.sha }}/operator.Dockerfile
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
    - name: "Docker: build operator image"
      uses: docker/build-push-action@v5
      with:
        push: false
        load: true
        tags: ${{ steps.meta-operator.outputs.tags }}
        labels: ${{ steps.meta-operator.outputs.labels }}
        file: ./operator.Dockerfile
    - name: "Docker: test operator image"
      run: docker run --rm "${{ fromJSON(steps.meta-operator.outputs.json).tags[0] }}" --help

    # Now is the turn of the worker image

    - name: "Docker: metadata-action for worker"
      id: meta-worker
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.worker_repository }}
        labels: |
          org.opencontainers.image.title=KubeKarma 
          org.opencontainers.image.url=https://github.com/cristiansteib/kubekarma/blob/${{ github.sha }}/worker.Dockerfile
    - name: "Docker: build worker image"
      uses: docker/build-push-action@v5
      with:
        push: false
        load: true
        tags: ${{ steps.meta-worker.outputs.tags }}
        labels: ${{ steps.meta-worker.outputs.labels }}
        file: ./worker.Dockerfile
    - name: "Docker: test worker image"
      run: docker run --rm `echo "${{ steps.meta-worker.outputs.tags }}" | head -1` --help

    # now push if requested
    - name: "Docker: publish worker image"
      uses: docker/build-push-action@v5
      with:
        push: ${{ inputs.push }}
        load: true
        tags: ${{ steps.meta-worker.outputs.tags }}
        labels: ${{ steps.meta-worker.outputs.labels }}
        file: ./worker.Dockerfile
    - name: "Docker: publish operator image"
      uses: docker/build-push-action@v5
      with:
        push: ${{ inputs.push }}
        load: true
        tags: ${{ steps.meta-operator.outputs.tags }}
        labels: ${{ steps.meta-operator.outputs.labels }}
        file: ./operator.Dockerfile